export const STRIPE_CONFIG = {
  // Prices
  BASIC_MONTHLY_PLAN_PRICE_ID: 'price_1RJumRJjRarA6eH84kygqd80',
  BASIC_YEARLY_PLAN_PRICE_ID: 'price_1RJumvJjRarA6eH8KTvJCoGL',
  STANDARD_MONTHLY_PLAN_PRICE_ID: 'price_standard_monthly',
  STANDARD_YEARLY_PLAN_PRICE_ID: 'price_standard_yearly',
  LIFETIME_PLAN_PRICE_ID: 'price_lifetime',
  
  // Price amounts (for display)
  BASIC_MONTHLY_PLAN_PRICE: 14.99,
  BASIC_YEARLY_PLAN_PRICE: 129.99,
  STANDARD_MONTHLY_PLAN_PRICE: 17.99,
  STANDARD_YEARLY_PLAN_PRICE: 179.99,
  LIFETIME_PLAN_PRICE: 99.00,
};