[build]
  command = "npm ci && npm install framer-motion@12.10.0 --save && npm run build"
  publish = "dist"

# Set environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 