
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fiumlujnbdfucihmaadd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpdW1sdWpuYmRmdWNpaG1hYWRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODMxMDEsImV4cCI6MjA2NTk1OTEwMX0.0DjsYzrF8v3qfz3mtnNtoWvopY6BVZdpUECbZsBrykk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window.localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
